name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file aws-cloudformation/web-app-with-cloudwatch.yaml \
            --stack-name MyWebServerStack \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset

      - name: Get Stack Outputs
        id: get-outputs
        run: |
          OUTPUTS=$(aws cloudformation describe-stacks \
            --stack-name MyWebServerStack \
            --query "Stacks[0].Outputs" \
            --output json)

          WEBSITE_URL=$(echo "$OUTPUTS" | jq -r '.[] | select(.OutputKey == "WebsiteURL") | .OutputValue')
          
          # This is the new line to save the URL to a file
          echo "$WEBSITE_URL" > ip.txt
          
          echo "The website URL is: $WEBSITE_URL"
          echo "The CloudWatch Dashboard URL is: ${{ steps.get-outputs.outputs.dashboard_url }}"
          
      # This is the new step to upload the IP file as an artifact
      - name: Upload IP Address Artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp-ip-address
          path: ip.txt
          retention-days: 1
